export enum ResponseStatus {
  ANALYZING = "ANALYZING",
  START_RESPONSE = "START_RESPONSE",
  START_DEFAULT_MESSAGE = "START_DEFAULT_MESSAGE",
  START_CANVAS_MESSAGE = "START_CANVAS_MESSAGE",
  DEFAULT_MESSAGE = "DEFAULT_MESSAGE",
  CANVAS_MESSAGE = "CANVAS_MESSAGE",
  STOP_CANVAS_MESSAGE = "STOP_CANVAS_MESSAGE",
  STOP_DEFAULT_MESSAGE = "STOP_DEFAULT_MESSAGE",
  END_RESPONSE = "END_RESPONSE",
  ANALYSIS_TIMEOUT = "ANALYSIS_TIMEOUT",
}
